### ISSUE TITLE
filebeat from docker

### ISSUE THREAD

**Issue by ondrejsika** [ondrejsika/elk-training#8]
`compse.yml`

```yaml
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.3
    user: 0:0
    command: filebeat -e
    network_mode: host
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - filebeat-data:/usr/share/filebeat/data:rw
volumes:
  filebeat-data:
```

`filebeat.yml`

```yaml
filebeat.inputs:
  - type: container
    paths:
      - "/var/lib/docker/containers/*/*.log"

# output.console:
#   pretty: true

output.elasticsearch:
  hosts:
    - https://es.k8s.sikademo.com:443
  username: elastic
  password: q3fv4NT1YB7L0yL4X27M30WI
```
